[package]
name = "boj-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
rand = "0.8.5"
scraper = "0.17.1"
ureq = "2.7.1"

[[bin]]
name = "boj-test"
path = "src/autocheck.rs"
